### ISSUE TITLE
Not working in Atom 137 and 138 on Windows.

### ISSUE THREAD

**Issue by gerane** [bigfive/atom-sublime-select#25] opened 2014-10-17 21:02 UTC
It just isn't working at all. Can't get the block selection to trigger.

**Comment by bigfive** [comment] 2015-01-13 05:20
Hmm. I guess this will be fixed when I implement configurable key options

**Comment by bigfive** [comment] 2015-01-29 08:46
Let me know if the latest patch helps. Its not configurable but it has more sensible windows key config

**Comment by papermoon1978** [comment] 2015-02-09 06:36
Doesn't work for me either > version 1.2.3 on Windows 7 atom 177. Maybe the issue is because the alt key triggers the menu bar? When I change it to 

 when 'win32'
    key: 'shiftKey'
    mouse: 1
    middleMouse: true

if works fine for me (when holding shift of course - but that's fine)

**Comment by bigfive** [comment] 2016-01-15 02:54
Keys are now configurable

**Closed by bigfive** 2016-01-15 02:54 UTC
