### ISSUE TITLE
Uncaught Error: Passed an empty array to setSelectedBufferRanges

### ISSUE THREAD

**Issue by jann** [bigfive/atom-sublime-select#30] opened 2014-12-15 13:55 UTC
Uncaught Error: Passed an empty array to setSelectedBufferRanges

**Atom Version**: 0.156.0
**System**: Mac OS X 10.10.1
**Thrown From**: [SublimeSelect](https://github.com/bigfive/atom-sublime-select) package, v0.4.2

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1713

Error: Passed an empty array to setSelectedBufferRanges
  at TextEditor.module.exports.TextEditor.setSelectedBufferRanges (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1713:15)
  at /Users/jan/.atom/packages/SublimeSelect/lib/sublime-select.coffee:65:14
  at atom-text-editor.<anonymous> (/Users/jan/.atom/packages/SublimeSelect/lib/sublime-select.coffee:43:9)
  at atom-text-editor.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at atom-text-editor.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-text-editor.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

/cc @atom/core

**Comment by bigfive** [comment] 2015-01-13 05:18
Yep I can reproduce this sometimes. I'll just add a length check to the setSelectedBufferRanges call

**Comment by bigfive** [comment] 2015-01-29 08:33
@TouPye As far as I know this is fixed in the new version

**Closed by bigfive** 2015-01-29 08:33 UTC

**Comment by TouPye** [comment] 2015-01-29 08:34
Confirmed, I couldn't reproduce :+1:
