### ISSUE TITLE
Chinese characters

### ISSUE THREAD

**Issue by durianskh** [bigfive/atom-sublime-select#73] opened 2015-10-15 12:33 UTC
can't select Chinese characters correctly

**Comment by jgkim** [comment] 2015-11-02 06:24
I also have this issue with other 2-byte characters such as Korean and Japanese.

**Comment by bigfive** [comment] 2016-01-15 02:50
Duplicate of https://github.com/bigfive/atom-sublime-select/issues/36

**Closed by bigfive** 2016-01-15 02:50 UTC
Labels: duplicate
