### ISSUE TITLE
Uncaught TypeError: editorBuffer.getLastRow is not a function

### ISSUE THREAD

**Issue by fabioarantes89** [bigfive/atom-sublime-select#114] opened 2016-08-23 18:56 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.9
**System**: Mac OS X 10.11.6
**Thrown From**: [Sublime-Style-Column-Selection](https://github.com/bigfive/atom-sublime-select) package, v1.7.2
### Stack Trace

Uncaught TypeError: editorBuffer.getLastRow is not a function

```
At /Users/web1/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:109

TypeError: editorBuffer.getLastRow is not a function
    at _screenPositionForMouseEvent (/Users/web1/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:109:32)
    at atom-text-editor.onMouseDown (/Users/web1/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:68:27)
```
### Commands

```
     -1:38.2.0 application:open (atom-text-editor.editor.is-focused)
     -1:09.0 core:close (div.panels-item)
  2x -0:23.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:22.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "php-server",
      "atom-x",
      "compile-watch",
      "terminal-plus",
      "pigments"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.7 (inactive)
atom-bootstrap4, v1.4.0 (active)
atom-jade, v0.3.0 (active)
atom-minify, v0.7.3 (active)
color-picker, v2.0.13 (active)
data-atom, v0.20.4 (active)
emmet, v2.3.12 (active)
html2jade-plus, v1.0.0 (inactive)
language-docker-erb, v0.1.0 (active)
language-swift, v0.4.0 (active)
minimap, v4.23.2 (active)
pigments, v0.32.1 (inactive)
Remote-FTP, v0.8.3 (active)
SFTP-deployment, v1.0.2 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (active)
swift-debugger, v0.1.2 (inactive)
terminal-plus, v0.14.5 (inactive)
uglify, v1.2.5 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by vujevits** [comment] 2016-09-27 09:16
Cannot use the package because this issue still persists

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.10.5
**Thrown From**: [sublime-style-column-selection](https://github.com/bigfive/atom-sublime-select) package, vundefined


### Stack Trace

Uncaught TypeError: this.editorBuffer.getLastRow is not a function

```
At /Users/vmark/.atom/packages/sublime-style-column-selection/lib/editor-handler.coffee:110

TypeError: this.editorBuffer.getLastRow is not a function
    at SublimeSelectEditorHandler.module.exports.SublimeSelectEditorHandler._screenPositionForMouseEvent (/Users/vmark/.atom/packages/sublime-style-column-selection/lib/editor-handler.coffee:92:58)
    at SublimeSelectEditorHandler.module.exports.SublimeSelectEditorHandler.onMouseDown (/Users/vmark/.atom/packages/sublime-style-column-selection/lib/editor-handler.coffee:41:27)
    at atom-text-editor.<anonymous> (/Users/vmark/.atom/packages/sublime-style-column-selection/lib/editor-handler.coffee:1:1)
```

### Commands

```
     -6:16.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -6:11.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:11.7.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -6:04.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:34 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:14.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:12.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:12.6.0 calculator:toggle (atom-text-editor.editor)
     -1:08.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 10x -1:04.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:57.4.0 incompatible-packages:view (atom-text-editor.editor)
     -0:52 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:48.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:48.6.0 settings-view:uninstall-packages (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined (inactive)
atom-typescript, v10.1.7 (active)
flatten-json, v0.1.4 (inactive)
highlight-selected, v0.11.2 (active)
keyboard-localization, v1.4.18 (active)
language-groovy, v0.6.0 (active)
language-haxe, v0.5.1 (active)
linter, v1.11.16 (active)
pretty-json, v1.6.0 (active)
Sublime-Style-Column-Selection, v1.7.2 (active)
xml-formatter, v0.10.0 (inactive)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lweingart** [comment] 2016-11-05 17:12
Hi there,

This issue seems to still be posing problems.

Steps to reproduce: just alt+click in a text file.

**Stacktrace**
Uncaught TypeError: editorBuffer.getLastRow is not a function
/Users/lweingart/.atom/packages/sublime-style-column-selection/lib/sublime-select.coffee:90
Hide Stack Trace
TypeError: editorBuffer.getLastRow is not a function
    at _screenPositionForMouseEvent (/Users/lweingart/.atom/packages/sublime-style-column-selection/lib/sublime-select.coffee:90:57)
    at atom-text-editor.onMouseDown (/Users/lweingart/.atom/packages/sublime-style-column-selection/lib/sublime-select.coffee:53:25)

**Installed Packages**
```
atom-dark-syntax@0.27.0
atom-dark-ui@0.52.0
atom-light-syntax@0.28.0
atom-light-ui@0.44.0
base16-tomorrow-dark-theme@1.2.0
base16-tomorrow-light-theme@1.2.0
one-dark-ui@1.6.0
one-light-ui@1.6.0
one-dark-syntax@1.3.0
one-light-syntax@1.3.0
solarized-dark-syntax@1.0.2
solarized-light-syntax@1.0.2
about@1.7.0
archive-view@0.61.1
autocomplete-atom-api@0.10.0
autocomplete-css@0.11.2
autocomplete-html@0.7.2
autocomplete-plus@2.31.1
autocomplete-snippets@1.11.0
autoflow@0.27.0
autosave@0.23.1
background-tips@0.26.1
bookmarks@0.42.0
bracket-matcher@0.82.1
command-palette@0.38.0
deprecation-cop@0.54.1
dev-live-reload@0.47.0
encoding-selector@0.22.0
exception-reporting@0.40.0
find-and-replace@0.201.1
fuzzy-finder@1.4.0
git-diff@1.1.0
go-to-line@0.31.0
grammar-selector@0.48.2
image-view@0.59.0
incompatible-packages@0.26.1
keybinding-resolver@0.35.0
line-ending-selector@0.5.0
link@0.31.1
markdown-preview@0.158.0
metrics@1.0.0
notifications@0.65.1
open-on-github@1.2.0
package-generator@1.0.0
settings-view@0.242.2-hotfix1
snippets@1.0.2
spell-check@0.68.2
status-bar@1.4.1
styleguide@0.47.0
symbols-view@0.113.1
tabs@0.101.0
timecop@0.33.2
tree-view@0.209.3
update-package-dependencies@0.10.0
welcome@0.35.1
whitespace@0.33.0
wrap-guide@0.38.2
language-c@0.52.1
language-clojure@0.21.0
language-coffee-script@0.47.2
language-csharp@0.12.1
language-css@0.37.1
language-gfm@0.88.0
language-git@0.15.0
language-go@0.42.1
language-html@0.45.1
language-hyperlink@0.16.0
language-java@0.23.0
language-javascript@0.119.0
language-json@0.18.2
language-less@0.29.5
language-make@0.22.2
language-mustache@0.13.0
language-objective-c@0.15.1
language-perl@0.35.0
language-php@0.37.2
language-property-list@0.8.0
language-python@0.45.0
language-ruby@0.69.0
language-ruby-on-rails@0.25.0
language-sass@0.56.0
language-shellscript@0.22.4
language-source@0.9.0
language-sql@0.23.0
language-text@0.7.1
language-todo@0.28.0
language-toml@0.18.0
language-xml@0.34.9
language-yaml@0.26.0

Sublime-Style-Column-Selection@1.7.2
android@0.1.0
atom-ethereum-interface@0.1.0-0
atom-html-preview@0.1.13
atom-markdown-katex@0.3.6
dash@1.3.0
go-playground@0.0.2
go-plus@3.5.1
kutt-ndk-debugger@0.2.0
language-apache@1.3.0
language-gradle@0.0.3
language-latex@0.6.1
language-scala@1.1.3
language-swift@0.4.0
latex@0.29.0
linter@1.8.1
linter-javac@1.9.4
linter-pep8@1.0.1
linter-scalac@1.0.2
linter-solidity@0.2.1
markdown-pdf@1.3.9
markdown-scroll-sync@0.4.2
markdown-toc@0.3.0
minimap@4.13.2
monokai@0.18.0
pdf-view@0.23.0
scala-format@0.1.8
script@3.10.1
seti-syntax@0.4.0
seti-ui@0.8.0
sort-lines@0.11.0
tabs-to-spaces@0.11.1
```

**Comment by bigfive** [comment] 2017-02-11 02:52
Fixed in recent release

**Closed by bigfive** 2017-02-11 02:52 UTC
