### ISSUE TITLE
Shifted selection with markdown-preview-mode on in Windows 7

### ISSUE THREAD

**Issue by gtaifu** [bigfive/atom-sublime-select#80] opened 2015-12-22 12:15 UTC
I am writing a markdown file, which contains multiple lines. After I press ctrl+shift+m to open the **markdown preview mode**, when I press alt-key to select vertically, the cursor starts at a position 30 characters right to the mouse cursor position.
Some times, cursor may also appear several lines higher.

**Comment by LeoToivio** [comment] 2016-01-06 09:01
Can confirm, doesn't work for me either.

**Comment by bigfive** [comment] 2016-01-15 02:26
You mean when trying to select text in a markdown preview?
Yeah, the package only supports selecting text in an editor pane. What is the markdown preview package you are using, I'll see if I can make sure the package does even activate if you are using a markdown preview pane?

**Comment by bigfive** [comment] 2016-01-15 03:01
Duplicate of https://github.com/bigfive/atom-sublime-select/issues/75

**Closed by bigfive** 2016-01-15 03:01 UTC
Labels: duplicate
