### ISSUE TITLE
Sublime style Column Selection does not work after Atom Update Version 1.9.0

### ISSUE THREAD

**Issue by Kungfoowiz** [bigfive/atom-sublime-select#109] opened 2016-08-02 09:54 UTC
Hello,

After updating to Atom Version 1.9.0, I do not seem to be able to column select text anymore with the Sublime style column selection plugin.

It was very useful, could you please check what caused it to stop working and perhaps release a fix for it to work in the new Atom Version 1.9.0?

Thank you very much,
Edward

**Comment by cbrnr** [comment] 2016-08-02 10:14
This problem has already been reported in #103 I think.

**Comment by gauthier-delacroix** [comment] 2016-08-11 10:10
@cbrnr These issues are supposed to be fixed by 1.7.2 but it still doesn't work for me on any 1.9.x version.

Tried to uninstall/reinstall the package, restart Atom, etc...still doesn't work just as if the package isn't installed...

**Comment by cbrnr** [comment] 2016-08-11 13:08
I'm on Atom 1.9.8, and the plugin is working (1.7.2)...

**Comment by gauthier-delacroix** [comment] 2016-08-11 14:44
Well, I've just tried disabling all other plugins and it's not better...I'll have to reset my config...

**Comment by gauthier-delacroix** [comment] 2016-08-11 14:54
Just renamed .atom folder to create a new one and the plugin works fine...just have to make my config again now :o(

**Comment by gauthier-delacroix** [comment] 2016-08-11 15:11
Ok, just understood my problem: When reinstalling the plugin before 1.7.2, my settings have been reset and I havent reset the select key to "None" since I only use the middle button...and I've since tried each of Alt and Middle button, but not both at the same time... Setting the key to "None" works as expected!

**Comment by cbrnr** [comment] 2016-08-12 07:17
So I guess this issue can be closed then.

**Comment by VoltairesPuppet** [comment] 2016-08-12 10:42
FYI.  I am also experiencing this problem.  It is as if block select mode is never triggered, will attempt to investigate further if I can reproduce this on another instance of Atom + Package.

**Comment by Kungfoowiz** [comment] 2016-08-16 08:15
Setting the modifier key to None and then back to Alt fixed this for me as well.

Using Atom 1.9.8.

Weird how it started working again...

**Comment by mattcodez** [comment] 2016-08-18 13:15
Using Atom 1.9.7 and plugin 1.7.2, can't get it to work at all. Tried changing key options but no luck.

**Comment by VoltairesPuppet** [comment] 2016-09-01 15:05
Is there an update log or something for Atom? I updated "script" plugin and possibly Atom and block selection has started working again.   Without knowing what was updated recently I am not sure if I can attribute it to something be "fixed" or just dumb luck.

**Closed** 2017-02-11 02:46 UTC
