### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pixelPositionForMouseEvent' of null

### ISSUE THREAD

**Issue by hinnerk** [bigfive/atom-sublime-select#39] opened 2015-02-27 14:04 UTC
[Enter steps to reproduce below:]

1. press `alt`
2. try to column-select

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [Sublime-Style-Column-Selection](https://github.com/bigfive/atom-sublime-select) package, v1.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'pixelPositionForMouseEvent' of null

```
At /Users/haardt/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:76

TypeError: Cannot read property 'pixelPositionForMouseEvent' of null
  at /Users/haardt/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:76:41
  at atom-text-editor.<anonymous> (/Users/haardt/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:49:23)

```

### Commands

```
     -3:04.4 core:move-up (atom-text-editor.editor.is-focused)
     -3:03.9 core:move-down (atom-text-editor.editor.is-focused)
     -1:24.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:18.9 core:copy (atom-text-editor.editor)
     -1:15.5 core:paste (atom-text-editor.editor.is-focused)
 26x -1:13.7 core:select-up (atom-text-editor.editor.is-focused)
     -1:10.5 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -1:10.5 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -1:09.7 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:09.7 snippets:expand (atom-text-editor.editor.is-focused)
     -1:09.7 editor:indent (atom-text-editor.editor.is-focused)
     -1:09.3 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:09.2 snippets:expand (atom-text-editor.editor.is-focused)
     -1:09.2 editor:indent (atom-text-editor.editor.is-focused)
     -1:08.3 core:move-left (atom-text-editor.editor.is-focused)
     -0:41.1 settings-view:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-iplastic-syntax.theme-atom-light-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-stream",
      "linter-write-good"
    ],
    "themes": [
      "atom-light-ui",
      "iplastic-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-beautify, v0.21.3
command-logger, v0.22.0
css-color-highlight, v0.3.0
dash, v1.0.2
esformatter, v1.3.0
file-icons, v1.4.11
git-log, v0.3.0
git-plus, v4.4.8
git-tab-status, v1.5.3
highlight-column, v0.3.2
highlight-line, v0.9.3
iplastic-syntax, v0.4.1
javascript-snippets, v1.0.0
jslint, v1.2.0
language-apache, v1.2.0
language-clojure, v0.13.0
language-docker, v1.1.2
language-generic-config, v0.1.3
language-ini, v1.7.0
language-latex, v0.4.1
language-log, v0.2.0
language-salt, v0.2.0
line-ending-converter, v1.0.0
linter, v0.12.0
linter-clojure, v0.0.4
linter-htmlhint, v0.0.8
linter-js-yaml, v1.0.0
linter-jscs, v1.7.0
linter-jshint, v0.1.0
linter-pep8, v0.1.0
linter-php, v0.0.11
linter-pyflakes, v0.0.4
linter-scss-lint, v0.0.14
log-console, v0.1.2
minimap, v4.3.1
open-last-project, v0.3.4
remote-edit, v1.6.4
space-tab, v0.1.0
ssh-config, v0.10.0
syntax-settings, v0.7.1
travis-ci-status, v0.11.2

# Dev
No dev packages
```

**Comment by gkrawiec** [comment] 2015-03-11 02:15
[Enter steps to reproduce below:]

1. ...press alt
2. ...try to column-select

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [Sublime-Style-Column-Selection](https://github.com/bigfive/atom-sublime-select) package, v1.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'pixelPositionForMouseEvent' of null

```
At /Users/gkrawiec/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:76

TypeError: Cannot read property 'pixelPositionForMouseEvent' of null
  at /Users/gkrawiec/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:76:41
  at atom-text-editor.<anonymous> (/Users/gkrawiec/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:49:23)

```

### Commands

```
     -3:48.1 core:undo (atom-text-editor.editor)
     -2:35.2 core:confirm (atom-text-editor.editor.mini)
     -2:19.2 core:backspace (atom-text-editor.editor.mini)
  3x -2:17.8 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "autocomplete-plus",
      "layout-manager"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atomatigit, v1.2.3
linter, v0.12.0
linter-erb, v0.1.0
linter-rubocop, v0.2.2
regex-railroad-diagram, v0.7.1
unity-ui, v2.0.5

# Dev
No dev packages
```

**Comment by karai17** [comment] 2015-03-15 08:13
This is an interesting bug, here is what happens to me:

1. I press ctrl+shift+M to view markdown preview of a markdown file
2. When I try to MMB-drag at the beginning of a row of text, it selects text several characters in (somewhere around 7 or 8)
3. I move the markdown file to the other view (I like to have my preview on the left and edit on my right)
4. When I try to MMB-drag, I get this error.

Restarting Atom fixes the issue, but I can consistently recreate this issue with the above steps.

**Atom Version**: 0.187.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [Sublime-Style-Column-Selection](https://github.com/bigfive/atom-sublime-select) package, v1.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'pixelPositionForMouseEvent' of null

```
At /c:/Users/Karai/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:105

TypeError: Cannot read property 'pixelPositionForMouseEvent' of null
  at C:\Users\Karai\.atom\packages\Sublime-Style-Column-Selection\lib\sublime-select.coffee:76:41
  at atom-text-editor.<anonymous> (C:\Users\Karai\.atom\packages\Sublime-Style-Column-Selection\lib\sublime-select.coffee:49:23)

```

### Commands

```
  2x -4:49.8 core:backspace (atom-text-editor.editor)
     -4:45.9 core:delete (atom-text-editor.editor)
undefined -4:37.1 find-and-replace:select-next (atom-text-editor.editor)
     -4:25.1 core:move-left (atom-text-editor.editor)
     -4:24.7 core:move-right (atom-text-editor.editor)
     -4:22.9 core:delete (atom-text-editor.editor)
  2x -4:20.2 core:move-left (atom-text-editor.editor)
 92x -4:08.8 find-and-replace:select-next (atom-text-editor.editor)
     -4:04.9 core:move-left (atom-text-editor.editor)
     -3:54.1 core:select-right (atom-text-editor.editor)
  7x -3:52.1 find-and-replace:select-next (atom-text-editor.editor)
  2x -3:38.9 core:delete (atom-text-editor.editor)
  3x -3:36.1 core:move-left (atom-text-editor.editor)
     -3:23.5 core:backspace (atom-text-editor.editor)
     -2:00.8 core:save (atom-text-editor.editor)
     -0:18.6 markdown-preview:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "language-objective-c",
      "language-clojure",
      "language-coffee-script",
      "language-go",
      "language-java",
      "language-less",
      "language-mustache",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-source",
      "language-toml",
      "welcome",
      "wrap-guide",
      "fuzzy-finder",
      "column-select",
      "firepad",
      "background-tips",
      "language-csharp",
      "language-git",
      "autoflow"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "ignoredNames": [
      "desktop.ini"
    ]
  }
}
```

### Installed Packages

```coffee
# User
build, v0.26.0
color-picker, v1.4.4
editorconfig, v0.3.2
language-lua, v0.9.0
minimap, v4.6.0
monokai, v0.12.0
project-manager, v1.15.5
slickedit-select, v1.3.0
Sublime-Style-Column-Selection, v1.2.3

# Dev
No dev packages
```

**Comment by benplumley** [comment] 2015-03-21 15:19
I'm getting this only with a split pane editor. It says block-cursor is throwing this but the stack trace says otherwise.

1. Split the editor into left and right panels
2. Open a file in both panels
3. Alt-click in the left panel to start this package

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [block-cursor](https://github.com/olmokramer/atom-block-cursor) package, v0.10.1

### Stack Trace

Uncaught TypeError: Cannot read property 'pixelPositionForMouseEvent' of null

```
At /C:/Users/Ben/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:105

TypeError: Cannot read property 'pixelPositionForMouseEvent' of null
  at C:\Users\Ben\.atom\packages\Sublime-Style-Column-Selection\lib\sublime-select.coffee:76:41
  at atom-text-editor.<anonymous> (C:\Users\Ben\.atom\packages\Sublime-Style-Column-Selection\lib\sublime-select.coffee:49:23)

```

### Commands

```
     -9:23.1 project-find:show (atom-text-editor.editor)
     -9:21.9 core:confirm (atom-text-editor.editor.mini)
     -9:04.9 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -9:04.9 core:cancel (atom-text-editor.editor.is-focused)
     -3:17.7 editor:toggle-line-comments (atom-text-editor.editor)
     -3:15.4 core:save (atom-text-editor.editor)
     -2:16.4 snippets:next-tab-stop (atom-text-editor.editor)
     -2:16.4 snippets:expand (atom-text-editor.editor)
  7x -2:09.6 core:backspace (atom-text-editor.editor)
     -2:06.0 core:move-right (atom-text-editor.editor)
     -1:48.3 core:save (atom-text-editor.editor)
  4x -1:39.3 core:delete (atom-text-editor.editor)
     -1:35.4 editor:newline (atom-text-editor.editor)
     -1:32.9 core:backspace (atom-text-editor.editor)
     -1:16.4 core:save (atom-text-editor.editor)
     -0:10.8 core:backspace (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "seti-monokai"
    ],
    "ignoredNames": [
      "*.class",
      "*.pdf",
      "*.xlsx"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "highlight-css-color"
    ]
  },
  "block-cursor": {
    "primaryColor": {
      "red": 0,
      "green": 255,
      "blue": 0,
      "alpha": 1
    },
    "secondaryColor": {
      "red": 29,
      "green": 31,
      "blue": 33,
      "alpha": 1
    },
    "preview": "The quick brown fox jumps over the lazy dog",
    "blinkInterval": 1000,
    "pulseDuration": 200
  }
}
```

### Installed Packages

```coffee
# User
block-cursor, v0.10.1
minimap, v4.6.0
seti-monokai, v0.3.1
Sublime-Style-Column-Selection, v1.2.3

# Dev
No dev packages
```

**Comment by shaungrady** [comment] 2015-06-18 18:15
[Enter steps to reproduce below:]

1. Hold middle mouse button and drag

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [Sublime-Style-Column-Selection](https://github.com/bigfive/atom-sublime-select) package, v1.3.0


### Stack Trace

Uncaught TypeError: Cannot read property 'pixelPositionForMouseEvent' of null

```
At /Users/shaun/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:85

TypeError: Cannot read property 'pixelPositionForMouseEvent' of null
  at _screenPositionForMouseEvent (/Users/shaun/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:85:41)
  at atom-text-editor.onMouseDown (/Users/shaun/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:53:25)

```

### Commands

```
     -0:44.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:44.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:42.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:32.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:31.2.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -0:31 core:paste (atom-text-editor.editor.is-focused)
     -0:27.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  5x -0:27 editor:add-selection-above (atom-text-editor.editor.is-focused)
     -0:25.7.0 core:paste (atom-text-editor.editor.is-focused)
  5x -0:21.2.0 editor:add-selection-below (atom-text-editor.editor.is-focused)
     -0:19.9.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:19.4.0 core:delete (atom-text-editor.editor.is-focused)
     -0:17.9.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:15.9.0 editor:lower-case (atom-text-editor.editor.is-focused)
     -0:11.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:11.1.0 aligner:align (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-dark-ui",
      "railscast-theme"
    ],
    "projectHome": "/Users/shaun/Repositories",
    "disabledPackages": [
      "atom-jade",
      "autocomplete-css",
      "autocomplete-paths"
    ],
    "destroyEmptyPanes": false,
    "followSymlinks": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Sublime-Style-Column-Selection, v1.3.0
aligner, v0.13.0
aligner-ruby, v1.4.0
angularjs, v0.3.0
atom-beautify, v0.28.5
atom-ternjs, v0.6.4
atom-typescript, v4.5.15
auto-reveal-in-sidebar, v0.5.0
block-travel, v1.0.2
color-picker, v2.0.5
emmet, v2.3.10
file-icons, v1.5.7
git-projects, v1.14.1
highlight-selected, v0.10.1
javascript-snippets, v1.0.0
language-haml, v0.21.0
language-jade, v0.4.0
linter, v0.12.7
linter-jshint, v0.1.6
linter-jsxhint, v0.1.2
linter-scss-lint, v1.0.4
pain-split, v1.4.0
project-manager, v1.15.10
railscast-theme, v0.3.0
react, v0.12.0
ruby-slim, v0.2.0

# Dev
No dev packages
```

**Comment by bigfive** [comment] 2016-01-15 02:40
I believe this issue is fixed in the new build. Since this PR was merged https://github.com/bigfive/atom-sublime-select/pull/70

**Closed** 2016-01-15 03:05 UTC
Labels: bug
