### ISSUE TITLE
unstable cursor and selection

### ISSUE THREAD

**Issue by kengz** [bigfive/atom-sublime-select#59] opened 2015-06-14 02:48 UTC
1. It takes considerable effort to select columns; selection flips between adjacent columns.
2. Occasionally the cursor/selection jumps to a random line in file. Not sure what causes that.

**Comment by vasyan** [comment] 2015-06-18 09:24
I have same problem, but i don't know how it reproduce. It just happens after couple of days of work. My solution is - Cmd + Shift + P and type Window: Reload .

**Comment by ksaff** [comment] 2015-07-22 18:10
I've observed the second issue as well. While `Window: Reload` is a usable work-around, I've found some steps for reproduction:
- `Window: Reload` to start fresh
- Column select something on an open document to ensure it works
- "Preview" the document- I used markdown-preview, but I have a hunch it's caused by the resizing of the document panel with Soft Wrap on
- Close the preview
- Try column highlighting the document
  - Should see some crazy offset.

**Comment by siannopollo** [comment] 2015-07-31 14:41
I was also able to reproduce this, much like @ksaff did, but I used the `rspec` package which opens a separate pane. As soon as that opened, the offset column selection began, and the normal behavior didn't return until I reloaded the window using the `Window: Reload` command.

**Comment by alexbet** [comment] 2015-10-20 16:18
+1 Not very useful as in Sublime. Jumping all around and even unselects the selection. Very frustrating.

**Comment by notno** [comment] 2015-12-09 23:50
+1 on issue number 2

**Comment by bigfive** [comment] 2016-01-15 02:47
@siannopollo The seperate pane issue is a duplicate of https://github.com/bigfive/atom-sublime-select/issues/34

Sounds like the unstable cursor position is to do with preview panes. I'll track that here https://github.com/bigfive/atom-sublime-select/issues/75

**Closed** 2016-01-15 02:47 UTC
Labels: duplicate
